version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/data:/app/data
    environment:
      - NODE_ENV=production

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
